ARCH=kvx
MACHINE=
SCRIPT_NAME=elf

# bundle with 1 nop insn
NOP=0x00f0037f

TEMPLATE_NAME=elf32
EXTRA_EM_FILE=kvxelf

OUTPUT_FORMAT="elf32-kvx"
TEXT_START_ADDR=0x0
MAXPAGESIZE="CONSTANT (MAXPAGESIZE)"
WRITABLE_RODATA=
GENERATE_SHLIB_SCRIPT=yes
