SCRIPT_NAME=elf
TEMPLATE_NAME=elf32
OUTPUT_FORMAT="elf64-k1"
MAXPAGESIZE="CONSTANT (MAXPAGESIZE)"
WRITABLE_RODATA=
ARCH=k1
TEXT_START_ADDR=0x20000000
GENERATE_SHLIB_SCRIPT=yes
OTHER_READONLY_SECTIONS="
  .rofixup        : {
    ${RELOCATING+__ROFIXUP_LIST__ = .;}
    *(.rofixup)
    ${RELOCATING+__ROFIXUP_END__ = .;}
  }
"
