
load_generic_config "unix"
process_multilib_options ""

# The default compiler for this target.
set_board_info compiler "k1cc -DPROTOTYPES"

# Can't do input (or output) in the current gdbserver.
set_board_info gdb,noinferiorio 1

# gdbserver does not intercept target file operations and perform them
# on the host.
set_board_info gdb,nofileio 1

set_board_info gdb,nosignals 1
set_board_info gdb,skip_huge_test 1


